// Code generated by goa, DO NOT EDIT.
//
// Code Generator
//
// Command:
// goa

package main

import (
	"flag"
	"fmt"
	"os"
	"runtime/debug"
	"strconv"
	"strings"
	"time"

	_ "example.com/assistant/design"
	"goa.design/goa/v3/codegen"
	"goa.design/goa/v3/codegen/generator"
	"goa.design/goa/v3/eval"
	goa "goa.design/goa/v3/pkg"
)

func main() {
	var (
		out     = flag.String("output", "", "")
		version = flag.String("version", "", "")
		cmdl    = flag.String("cmd", "", "")
		debug   = flag.Bool("debug", false, "")
		ver     int
	)
	{
		flag.Parse()
		if *out == "" {
			fail("missing output flag")
		}
		if *version == "" {
			fail("missing version flag")
		}
		if *cmdl == "" {
			fail("missing cmd flag")
		}
		v, err := strconv.Atoi(*version)
		if err != nil {
			fail("invalid version %s", *version)
		}
		ver = v
	}

	startBinary := time.Now()
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Starting generated binary execution\n")
	}

	if ver > goa.Major {
		fail("cannot run goa %s on design using goa v%s\n", goa.Version(), *version)
	}

	startCheckErrors := time.Now()
	if err := eval.Context.Errors; err != nil {
		fail(err.Error())
	}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Check eval.Context.Errors took %v\n", time.Since(startCheckErrors))
	}

	startRunDSL := time.Now()
	if err := eval.RunDSL(); err != nil {
		fail(err.Error())
	}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] eval.RunDSL() took %v\n", time.Since(startRunDSL))
	}
	codegen.DesignVersion = ver

	startGenerate := time.Now()
	outputs, err := generate(*out, "example", *debug)
	if err != nil {
		fail(err.Error())
	}
	if *debug {
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] generator.Generate() took %v\n", time.Since(startGenerate))
		fmt.Fprintf(os.Stderr, "[TIMING]   [binary] Total binary execution took %v\n", time.Since(startBinary))
	}
	fmt.Println(strings.Join(outputs, "\n"))
}

// generate runs code generation and converts panics into a bug report
// request: Goa generators panic on internal invariant violations, and this
// recover is the single boundary turning them into actionable output. Design
// errors never reach this point; eval.RunDSL reports them before generation.
func generate(out, cmd string, dbg bool) ([]string, error) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintf(os.Stderr, "panic: %v\n\n%s\n", r, debug.Stack())
			fail("This is a bug in Goa, please report it at https://github.com/goadesign/goa/issues and include the stack trace above together with the design that triggered it.\n")
		}
	}()
	return generator.Generate(out, cmd, dbg)
}

func fail(msg string, vals ...any) {
	fmt.Fprintf(os.Stderr, msg, vals...)
	os.Exit(1)
}
