// Code generated by goa, DO NOT EDIT.
//
// Agents bootstrap (internal)
//
// Command:
// $ goa example example.com/quickstart/design

package bootstrap

import (
	"context"
	"fmt"

	chat "example.com/quickstart/gen/orchestrator/agents/chat"
	gentoolchathelpers "example.com/quickstart/gen/orchestrator/toolsets/helpers"
	plannerchat "example.com/quickstart/internal/agents/chat/planner"
	"goa.design/goa-ai/runtime/agent/planner"
	agentsruntime "goa.design/goa-ai/runtime/agent/runtime"
)

// Package bootstrap wires the goa-ai runtime and registers generated agents.
// This scaffold is application-owned: edit and maintain it; it is not re-generated
// by `goa gen`. Use it from your cmd main or workers to initialize agents.

// Define flags for MCP endpoints (if any). Pass values via your cmd main.

// New constructs a minimal runtime and registers all agents for this service.
// Replace options (engine, stores, telemetry) as you adopt production wiring.
func New(ctx context.Context) (*agentsruntime.Runtime, func(), error) {
	rt := agentsruntime.New()
	cleanup := func() {}

	// Register agents with example planners. Replace with your own planner impls.
	{
		cfg := chat.ChatAgentConfig{Planner: plannerchat.New()}
		if err := chat.RegisterChatAgent(ctx, rt, cfg); err != nil {
			return nil, nil, err
		}
		// Register deterministic executors so the generated example runs one
		// complete typed tool round trip before application code is added.
		if err := chat.RegisterUsedToolsets(ctx, rt,
			chat.WithHelpersExecutor(agentsruntime.ToolCallExecutorFunc(
				func(ctx context.Context, _ *agentsruntime.ToolCallMeta, call *agentsruntime.ToolCall) (*agentsruntime.ToolExecutionResult, error) {
					if call == nil {
						return nil, fmt.Errorf("tool request is nil")
					}
					switch call.Name {
					case gentoolchathelpers.Answer:
						if _, err := gentoolchathelpers.SpecAnswer.Payload.Codec.FromJSON(call.Payload); err != nil {
							return nil, fmt.Errorf("decode helpers.answer example payload: %w", err)
						}
						result, err := gentoolchathelpers.AnswerResultCodec.FromJSON(
							[]byte("{\"text\":\"Tokyo is the capital of Japan.\"}"),
						)
						if err != nil {
							return nil, fmt.Errorf("decode helpers.answer example result: %w", err)
						}
						return agentsruntime.Executed(&planner.ToolResult{Name: call.Name, Result: result}), nil
					default:
						return nil, fmt.Errorf("unknown example tool %q", call.Name)
					}
				},
			)),
		); err != nil {
			return nil, nil, err
		}
	}

	return rt, cleanup, nil
}
