// Code generated by goa v3.23.4, DO NOT EDIT.
//
// Agents bootstrap (internal)
//
// Command:
// $ goa example example.com/quickstart/design

package bootstrap

import (
	"context"

	chat "example.com/quickstart/gen/orchestrator/agents/chat"
	plannerchat "example.com/quickstart/internal/agents/chat/planner"
	agentsruntime "goa.design/goa-ai/runtime/agent/runtime"
)

// Package bootstrap wires the goa-ai runtime and registers generated agents.
// This scaffold is application-owned: edit and maintain it; it is not re-generated
// by `goa gen`. Use it from your cmd main or workers to initialize agents.

// Define flags for MCP endpoints (if any). Pass values via your cmd main.

// New constructs a minimal runtime and registers all agents for this service.
// Replace options (engine, stores, telemetry) as you adopt production wiring.
func New(ctx context.Context) (*agentsruntime.Runtime, func(), error) {
	rt := agentsruntime.New()
	cleanup := func() {}

	// Register agents with example planners. Replace with your own planner impls.
	{
		cfg := chat.ChatAgentConfig{Planner: plannerchat.New()}
		if err := chat.RegisterChatAgent(ctx, rt, cfg); err != nil {
			return nil, nil, err
		}
	}

	return rt, cleanup, nil
}
