// Package bootstrap wires the goa-ai runtime and registers generated agents.
// This scaffold was created by goa example and is application-owned: edit and
// maintain it; it is not re-generated by `goa gen`. Use it from your cmd main
// or workers to initialize agents.
package bootstrap

import (
	"context"

	genchat "example.com/quickstart/gen/orchestrator/agents/chat"
	plannerchat "example.com/quickstart/internal/agents/chat/planner"
	helpersexec "example.com/quickstart/internal/agents/chat/toolsets/helpers"
	agentsruntime "goa.design/goa-ai/runtime/agent/runtime"
)

// New constructs a minimal runtime and registers all agents for this service.
// Replace options (engine, stores, telemetry) as you adopt production wiring.
func New(ctx context.Context) (*agentsruntime.Runtime, func(), error) {
	rt := agentsruntime.New()
	cleanup := func() {}

	// Register agents with their planners.
	{
		cfg := genchat.ChatAgentConfig{Planner: plannerchat.New()}
		if err := genchat.RegisterChatAgent(ctx, rt, cfg); err != nil {
			return nil, nil, err
		}
		// Wire the executor for every toolset the agent uses. The generated
		// helper fails fast when an executor is missing.
		if err := genchat.RegisterUsedToolsets(ctx, rt,
			genchat.WithHelpersExecutor(agentsruntime.ToolCallExecutorFunc(helpersexec.Execute)),
		); err != nil {
			return nil, nil, err
		}
	}

	return rt, cleanup, nil
}
