package runtime

// workflow.go implements the durable plan/tool loop executed inside a workflow engine.
//
// Contract:
// - The workflow loop is deterministic and replay-safe: timeouts use workflow time.
// - The loop publishes lifecycle and tool events via hooks for streaming and persistence.
// - Helper methods in sibling workflow_*.go files are invoked by this loop; callers should
//   not call them directly outside of workflow execution.

import (
	"context"
	"errors"
	"fmt"
	"time"

	"goa.design/goa-ai/runtime/agent/api"
	"goa.design/goa-ai/runtime/agent/engine"
	"goa.design/goa-ai/runtime/agent/hooks"
	"goa.design/goa-ai/runtime/agent/model"
	"goa.design/goa-ai/runtime/agent/planner"
	"goa.design/goa-ai/runtime/agent/run"
	"goa.design/goa-ai/runtime/agent/telemetry"
)

const (
	// defaultFinalizerGrace is the default extension from Budget to Hard.
	defaultFinalizerGrace = 10 * time.Second
)

// ExecuteWorkflow is the main entry point for the generated workflow handler.
//
// Advanced & generated integration
//   - Intended to be invoked by code generated by goa-ai during agent
//     registration, or by advanced users writing custom engine adapters.
//   - Normal applications should prefer the high‑level AgentClient API
//     (Runtime.Client(...).Run/Start) rather than calling this directly.
//
// It executes the agent's plan/tool loop using the configured planner, policy,
// and runtime hooks. Returns the final agent output or an error if the workflow
// fails. Generated code calls this from the workflow handler registered with
// the engine.
func (r *Runtime) ExecuteWorkflow(wfCtx engine.WorkflowContext, input *RunInput) (*RunOutput, error) {
	if err := validateWorkflowRunInput(input); err != nil {
		return nil, err
	}
	if r.logger != nil {
		r.logger.Info(wfCtx.Context(), "ExecuteWorkflow called", "agent_id", input.AgentID, "run_id", input.RunID)
	}
	if input.AgentID == "" {
		return nil, errors.New("agent id is required")
	}
	defer func() {
		r.storeWorkflowHandle(input.RunID, nil)
		if r.reminders != nil {
			r.reminders.ClearRun(input.RunID)
		}
	}()
	reg, ok := r.agentByID(input.AgentID)
	if !ok {
		return nil, fmt.Errorf("agent %q is not registered", input.AgentID)
	}
	var checkpoint *workflowCheckpoint
	if input.Continuation != nil {
		var err error
		checkpoint, err = r.decodeWorkflowCheckpoint(input.Continuation.Suspension)
		if err != nil {
			return nil, err
		}
		if err := restoreContinuationRunInput(input, checkpoint); err != nil {
			return nil, err
		}
	}
	if err := r.validateCompletionToolPolicy(reg, input.Policy); err != nil {
		return nil, err
	}
	if err := validateCompletionToolWorkflowRetry(input.Policy, input.WorkflowOptions); err != nil {
		return nil, err
	}
	if input.Policy != nil {
		if err := r.validateLimitTerminalPlans(reg, input.Policy.LimitTerminalPlans); err != nil {
			return nil, err
		}
	}
	r.logger.Info(wfCtx.Context(), "Agent found, executing plan activity", "agent_id", input.AgentID)
	// Policy decisions merge additional labels into input.Labels in place during
	// the run loop; the terminal RunCompleted event must carry the run-scoped
	// labels as provided at start, so capture them before the loop runs.
	startLabels := cloneLabels(input.Labels)
	runCtx := run.Context{
		RunID:            input.RunID,
		SessionID:        input.SessionID,
		TurnID:           input.TurnID,
		ParentToolCallID: input.ParentToolCallID,
		ParentRunID:      input.ParentRunID,
		ParentAgentID:    input.ParentAgentID,
		Tool:             input.Tool,
		ToolArgs:         input.ToolArgs,
		Attempt:          1,
		Labels:           input.Labels,
		Metadata:         input.Metadata,
	}
	// Get turn ID for event stamping
	turnID := input.TurnID
	if err := r.publishHook(
		wfCtx.Context(),
		hooks.NewRunStartedEvent(input.RunID, input.AgentID, runCtx, runStartedHookInput(input)),
		turnID,
	); err != nil {
		return nil, err
	}
	// Initial phase: input has been received and planning is about to begin.
	if err := r.publishHook(
		wfCtx.Context(),
		hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhasePrompted),
		turnID,
	); err != nil {
		return nil, err
	}
	finalStatus := runStatusSuccess
	var (
		finalErr        error
		finalSuspension *api.RunSuspension
	)
	defer func() {
		// Use a fresh context with timeout for terminal events. The workflow
		// engine supplies a replay-aware context so subscribers can avoid
		// re-applying side effects during history replay while still allowing
		// session stores and UIs to observe one terminal phase.
		//
		// Emit only RunCompletedEvent or RunSuspendedEvent (each carries its
		// terminal phase). Emitting a separate RunPhaseChangedEvent first causes
		// two terminal workflow events to reach subscribers, which can trigger
		// race conditions in frontends that close streams on the first
		// terminal event.
		detached := wfCtx.Detached()
		termCtx, cancel := context.WithTimeout(detached.Context(), 10*time.Second)
		defer cancel()
		if finalSuspension != nil {
			if err := r.publishHookWithOptions(
				termCtx,
				hooks.NewRunSuspendedEvent(
					input.RunID,
					input.AgentID,
					input.SessionID,
					finalSuspension.ID,
					finalSuspension.Version,
					len(finalSuspension.Pending),
					finalSuspension.RequiredTools,
				),
				turnID,
				engine.ActivityOptions{ScheduleToCloseTimeout: 10 * time.Second},
			); err != nil {
				r.logWarn(termCtx, "run suspended hook failed", err, "run_id", input.RunID, "agent_id", input.AgentID)
			}
			return
		}
		phase := terminalRunPhaseForStatus(finalStatus)
		completed, buildErr := r.buildRunCompletedEvent(
			termCtx,
			input.RunID,
			input.AgentID,
			input.SessionID,
			finalStatus,
			phase,
			startLabels,
			finalErr,
		)
		if buildErr != nil {
			r.logWarn(termCtx, "run completion build failed", buildErr, "run_id", input.RunID, "agent_id", input.AgentID)
			return
		}
		if err := r.publishHookWithOptions(
			termCtx,
			completed,
			turnID,
			engine.ActivityOptions{
				ScheduleToCloseTimeout: 10 * time.Second,
			},
		); err != nil {
			r.logWarn(termCtx, "run completed hook failed", err, "run_id", input.RunID, "agent_id", input.AgentID)
		}
	}()
	if checkpoint != nil {
		if len(checkpoint.BaseMessages) > 0 {
			// A continuation starts a distinct run from the complete planner
			// transcript restored from the predecessor checkpoint. Record that
			// transcript as this run's seed before appending the external
			// response so the successor remains independently replayable.
			if err := r.publishTranscriptSeed(
				wfCtx.Context(),
				input.RunID,
				input.AgentID,
				input.SessionID,
				turnID,
				checkpoint.BaseMessages,
			); err != nil {
				finalErr = err
				finalStatus = terminalRunStatusForError(err)
				return nil, err
			}
		}
		if err := r.publishHook(
			wfCtx.Context(),
			hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhaseExecutingTools),
			turnID,
		); err != nil {
			finalErr = err
			finalStatus = terminalRunStatusForError(err)
			return nil, err
		}
		out, err := r.resumeSuspendedWorkflow(wfCtx, reg, input, checkpoint)
		if err != nil {
			finalErr = err
			finalStatus = terminalRunStatusForError(err)
			return nil, err
		}
		finalSuspension = out.Suspension
		return out, nil
	}

	planInput := &planner.PlanInput{
		Messages:   input.Messages,
		RunContext: runCtx,
	}
	if len(input.Messages) > 0 {
		// Seed the run transcript with the exact planner input. These messages are
		// durable for replay/snapshots but are not newly committed conversation
		// output for this run, so they must not be published as appended deltas.
		if err := r.publishTranscriptSeed(
			wfCtx.Context(),
			input.RunID,
			input.AgentID,
			input.SessionID,
			turnID,
			input.Messages,
		); err != nil {
			finalErr = err
			finalStatus = terminalRunStatusForError(err)
			return nil, err
		}
	}
	// Materialize one active cap state before planning so ordinary tools,
	// recovery turns, and terminal finalization all observe the same run budget.
	caps := initialCaps(reg.Policy)
	if input.Policy != nil {
		if input.Policy.MaxToolCalls > 0 {
			caps.MaxToolCalls = input.Policy.MaxToolCalls
			caps.RemainingToolCalls = input.Policy.MaxToolCalls
		}
		if input.Policy.MaxRecoveryTurns > 0 {
			caps.MaxRecoveryTurns = input.Policy.MaxRecoveryTurns
			caps.RemainingRecoveryTurns = input.Policy.MaxRecoveryTurns
		}
	}
	st := &runLoopState{Caps: caps}
	// Compute deadlines before the initial Plan so it cannot outlive the run window.
	timing := resolveRunTiming(reg, input)
	timeBudget := timing.TimeBudget
	grace := timing.FinalizerGrace
	var (
		budgetDeadline time.Time
		hardDeadline   time.Time
	)
	if timeBudget > 0 {
		budgetDeadline = wfCtx.Now().Add(timeBudget)
		hardDeadline = budgetDeadline.Add(grace)
	}
	startReq := PlanActivityInput{
		AgentID:    input.AgentID,
		RunID:      input.RunID,
		Messages:   input.Messages,
		RunContext: runCtx,
		Policy:     clonePolicyOverrides(input.Policy),
	}
	if err := enforcePlanActivityInputBudget(startReq); err != nil {
		finalErr = err
		finalStatus = runStatusFailed
		return nil, err
	}
	// Apply run-level Plan timeout override when provided.
	planOpts := reg.PlanActivityOptions
	if input.Policy != nil && input.Policy.PlanTimeout > 0 {
		planOpts.StartToCloseTimeout = input.Policy.PlanTimeout
	}
	// Emit timing resolution for observability.
	if r.logger != nil {
		var planTimeout time.Duration
		if planOpts.StartToCloseTimeout > 0 {
			planTimeout = planOpts.StartToCloseTimeout
		}
		toolTimeout := reg.ExecuteToolActivityOptions.StartToCloseTimeout
		if toolTimeout == 0 {
			toolTimeout = defaultExecuteToolActivityTimeout
		}
		if input.Policy != nil && input.Policy.ToolTimeout > 0 {
			toolTimeout = input.Policy.ToolTimeout
		}
		r.logger.Info(wfCtx.Context(), "timing_resolved",
			"time_budget", timeBudget,
			"finalizer_grace", grace,
			"hard_deadline", hardDeadline,
			"plan_timeout", planTimeout,
			"tool_timeout", toolTimeout,
		)
	}
	// Transition into planning before invoking the planner activity.
	if err := r.publishHook(
		wfCtx.Context(),
		hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhasePlanning),
		turnID,
	); err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	firstOutput, err := r.runPlanActivity(wfCtx, reg.PlanActivityName, planOpts, startReq, budgetDeadline)
	if err != nil {
		if errors.Is(err, engine.ErrPlannerActivityDeadlineExceeded) &&
			!budgetDeadline.IsZero() {
			out, finalizeErr := r.finalizeRun(
				wfCtx,
				reg,
				input,
				planInput,
				nil,
				nil,
				model.TokenUsage{},
				caps,
				planInput.RunContext.Attempt+1,
				turnID,
				nil,
				planner.TerminationReasonTimeBudget,
				hardDeadline,
			)
			if finalizeErr != nil {
				finalErr = finalizeErr
				finalStatus = terminalRunStatusForError(finalizeErr)
				return nil, finalizeErr
			}
			finalStatus = runStatusSuccess
			return out, nil
		}
		r.logger.Error(wfCtx.Context(), "Plan activity failed", "error", err)
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	if firstOutput == nil {
		r.logger.Error(wfCtx.Context(), "Plan activity returned nil output")
		finalErr = fmt.Errorf("plan activity returned nil output")
		finalStatus = runStatusFailed
		return nil, finalErr
	}
	result := firstOutput.Result
	if result == nil &&
		firstOutput.OutputContractFailure == nil &&
		firstOutput.ModelInvocationRecovery == nil {
		finalErr = fmt.Errorf("plan activity returned neither result nor output rejection")
		finalStatus = runStatusFailed
		return nil, finalErr
	}
	if result != nil {
		r.logger.Info(wfCtx.Context(), "Plan activity completed", "tool_calls", len(result.ToolCalls), "final_response", result.FinalResponse != nil)
	}
	// Deadlines (budgetDeadline, hardDeadline, grace) already computed above.
	nextAttempt := planInput.RunContext.Attempt + 1
	st.NextAttempt = nextAttempt
	st.AggUsage = firstOutput.Usage
	st.Result = firstOutput.Result
	st.Transcript = firstOutput.Transcript
	if firstOutput.OutputContractFailure != nil {
		st.PendingRecovery = pendingModelOutputRecovery{
			correction: firstOutput.OutputContractFailure.Correction,
		}
	}
	if firstOutput.ModelInvocationRecovery != nil {
		st.PendingRecovery = pendingModelInvocationRecovery{
			correction: firstOutput.ModelInvocationRecovery.Correction,
		}
	}
	// Create parentTracker if this is a nested agent run (has ParentToolCallID)
	var parentTracker *childTracker
	if planInput.RunContext.ParentToolCallID != "" {
		parentTracker = newChildTracker(planInput.RunContext.ParentToolCallID)
	}
	// Enter tool execution phase for the main run loop.
	if err := r.publishHook(
		wfCtx.Context(),
		hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhaseExecutingTools),
		turnID,
	); err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	out, err := r.runLoopWithState(
		wfCtx,
		reg,
		input,
		planInput,
		st,
		budgetDeadline,
		hardDeadline,
		turnID,
		parentTracker,
	)
	if err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	// Successful completion.
	finalStatus = runStatusSuccess
	finalErr = nil
	finalSuspension = out.Suspension
	return out, nil
}

func (r *Runtime) runLoopWithState(
	wfCtx engine.WorkflowContext,
	reg AgentRegistration,
	input *RunInput,
	base *planner.PlanInput,
	st *runLoopState,
	budgetDeadline time.Time,
	hardDeadline time.Time,
	turnID string,
	parentTracker *childTracker,
) (*RunOutput, error) {
	if base == nil {
		return nil, errors.New("base plan input is required")
	}
	ctx := wfCtx.Context()
	if r.logger == nil {
		r.logger = telemetry.NoopLogger{}
	}
	if st == nil {
		return nil, errors.New("runLoop state is required")
	}
	if st.Result == nil && st.PendingRecovery == nil {
		return nil, fmt.Errorf("runLoop initial PlanResult is nil")
	}
	if st.Result != nil &&
		len(st.Result.ToolCalls) == 0 &&
		st.Result.FinalResponse == nil &&
		st.Result.FinalToolResult == nil &&
		st.Result.Await == nil {
		return nil, fmt.Errorf("runLoop initial PlanResult has no ToolCalls, FinalResponse, FinalToolResult, or Await")
	}
	if st.Result != nil {
		r.logger.Info(ctx,
			"runLoop starting iteration",
			"tool_calls",
			len(st.Result.ToolCalls),
			"final_response",
			st.Result.FinalResponse != nil,
			"final_tool_result",
			st.Result.FinalToolResult != nil,
			"await",
			st.Result.Await != nil,
		)
	}
	// Derive per-run overrides for Resume and Tools.
	resumeOpts := reg.ResumeActivityOptions
	if input.Policy != nil && input.Policy.PlanTimeout > 0 {
		resumeOpts.StartToCloseTimeout = input.Policy.PlanTimeout
	}
	toolOpts := reg.ExecuteToolActivityOptions
	if input.Policy != nil && input.Policy.ToolTimeout > 0 {
		toolOpts.StartToCloseTimeout = input.Policy.ToolTimeout
	}
	if toolOpts.StartToCloseTimeout == 0 {
		toolOpts.StartToCloseTimeout = defaultExecuteToolActivityTimeout
	}

	loop := newWorkflowLoop(
		r,
		wfCtx,
		reg,
		input,
		base,
		st,
		turnID,
		parentTracker,
		runDeadlines{
			Budget: budgetDeadline,
			Hard:   hardDeadline,
		},
		resumeOpts,
		toolOpts,
	)
	return loop.run()
}
