version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    lll:
      line-length: 120
      tab-width: 4
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: strict
    paths:
      - design/*
      - diagram/*
      - gql/*
      - mocks/*
issues:
  exclude-rules:
    - path: ".*/dsl/.*"
      linters:
        - staticcheck
      text: "ST1001: should not use dot imports"
