version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    unparam:
      check-exported: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: strict
    paths:
      - design/*
      - diagram/*
      - gql/*
      - mocks/*
      - agents/codegen/tests/testscenarios/*
