version: "2"

linters:
  enable:
    - errorlint
    - errcheck
    - staticcheck
    - unparam
    - unused
    - ineffassign
    - bodyclose
    - gocritic
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - nilerr
    - copyloopvar
    - sqlclosecheck
    - makezero
  settings:
    staticcheck:
      checks:
        - "-ST1001"   # Dot imports are used intentionally in DSL
    nakedret:
      max-func-lines: 30
    misspell:
      ignore-rules:
        - Statuser

issues:
  exclude-rules:
    # Exclude generated/example code from linting
    - path: ^example/.*/gen/
    - path: ^example/.*/goa.*
    - path: ^goa\.
