// Code generated by goa v3.23.4, DO NOT EDIT.
//
// Example main for orchestrator
//
// Command:
// $ goa example example.com/quickstart/design

package main

import (
	"context"
	"fmt"
	"log"

	chat "example.com/quickstart/gen/orchestrator/agents/chat"
	"example.com/quickstart/internal/agents/bootstrap"
	model "goa.design/goa-ai/runtime/agent/model"
)

// This example main demonstrates running the agent using the generated bootstrap.
// Replace or extend this as needed for your production deployment.

func main() {
	ctx := context.Background()

	// Initialize the runtime using the generated bootstrap which wires
	// planners and toolsets for all agents.
	rt, cleanup, err := bootstrap.New(ctx)
	if err != nil {
		log.Fatalf("failed to initialize runtime: %v", err)
	}
	defer cleanup()

	// Example: run the first registered agent with a simple message.
	// Replace this with your own CLI, HTTP server, or integration.

	{
		client := chat.NewClient(rt)
		out, err := client.Run(ctx, "demo-session", []*model.Message{
			{
				Role:  model.ConversationRoleUser,
				Parts: []model.Part{model.TextPart{Text: "Hello"}},
			},
		})
		if err != nil {
			log.Fatalf("agent run failed: %v", err)
		}
		fmt.Println("RunID:", out.RunID)
		if out.Final != nil && len(out.Final.Parts) > 0 {
			if tp, ok := out.Final.Parts[0].(model.TextPart); ok {
				fmt.Println("Assistant:", tp.Text)
			}
		}
	}

}
