// Code generated by goa v3.25.3, DO NOT EDIT.
//
// Example main for orchestrator
//
// Command:
// $ goa example example.com/quickstart/design

package main

import (
	"context"
	"fmt"
	"io"
	"log"

	chat "example.com/quickstart/gen/orchestrator/agents/chat"
	"example.com/quickstart/gen/orchestrator/completions"
	"example.com/quickstart/internal/agents/bootstrap"
	model "goa.design/goa-ai/runtime/agent/model"
	"goa.design/goa-ai/runtime/agent/rawjson"
)

// This example main demonstrates running the agent using the generated bootstrap.
// Replace or extend this as needed for your production deployment.

// exampleCompletionClient is a tiny structured-output model client used by the
// generated example main to demonstrate typed completion helpers without
// requiring a real provider integration.
type exampleCompletionClient struct {
	name    string
	payload []byte
}

// exampleCompletionStreamer emits one preview delta plus one canonical
// completion payload so the generated example exercises both streaming helper
// paths and final-chunk decoding.
type exampleCompletionStreamer struct {
	name    string
	payload []byte
	step    int
}

// newExampleCompletionClient constructs the example structured-output client
// from the generated completion example payload.
func newExampleCompletionClient(name string, payload []byte) (model.Client, error) {
	if len(payload) == 0 {
		return nil, fmt.Errorf("completion %q example JSON is required for generated example", name)
	}
	return &exampleCompletionClient{
		name:    name,
		payload: append([]byte(nil), payload...),
	}, nil
}

// validateRequest enforces the structured-output contract expected by the
// generated completion helpers.
func (c *exampleCompletionClient) validateRequest(req *model.Request, stream bool) error {
	if req == nil {
		return fmt.Errorf("completion %q request is nil", c.name)
	}
	if req.Stream != stream {
		return fmt.Errorf("completion %q stream=%t; expected %t", c.name, req.Stream, stream)
	}
	if req.StructuredOutput == nil {
		return fmt.Errorf("completion %q requires structured output", c.name)
	}
	if req.StructuredOutput.Name != c.name {
		return fmt.Errorf("completion %q received structured output %q", c.name, req.StructuredOutput.Name)
	}
	if len(req.StructuredOutput.Schema) == 0 {
		return fmt.Errorf("completion %q requires a structured output schema", c.name)
	}
	return nil
}

// Complete returns the canonical assistant JSON payload for unary completion
// examples.
func (c *exampleCompletionClient) Complete(_ context.Context, req *model.Request) (*model.Response, error) {
	if err := c.validateRequest(req, false); err != nil {
		return nil, err
	}
	return &model.Response{
		Content: []model.Message{
			{
				Role: model.ConversationRoleAssistant,
				Parts: []model.Part{
					model.TextPart{Text: string(c.payload)},
				},
			},
		},
	}, nil
}

// Stream emits a preview fragment followed by the canonical completion payload.
func (c *exampleCompletionClient) Stream(_ context.Context, req *model.Request) (model.Streamer, error) {
	if err := c.validateRequest(req, true); err != nil {
		return nil, err
	}
	return &exampleCompletionStreamer{
		name:    c.name,
		payload: append([]byte(nil), c.payload...),
	}, nil
}

// Recv advances the example stream through a single preview delta and the final
// canonical completion payload.
func (s *exampleCompletionStreamer) Recv() (model.Chunk, error) {
	switch s.step {
	case 0:
		s.step++
		end := min(len(s.payload), 24)
		return model.Chunk{
			Type: model.ChunkTypeCompletionDelta,
			CompletionDelta: &model.CompletionDelta{
				Name:  s.name,
				Delta: string(s.payload[:end]),
			},
		}, nil
	case 1:
		s.step++
		return model.Chunk{
			Type: model.ChunkTypeCompletion,
			Completion: &model.Completion{
				Name:    s.name,
				Payload: rawjson.Message(append([]byte(nil), s.payload...)),
			},
		}, nil
	default:
		return model.Chunk{}, io.EOF
	}
}

// Close releases example streamer resources.
func (s *exampleCompletionStreamer) Close() error {
	return nil
}

// Metadata returns no provider-specific metadata for the example stream.
func (s *exampleCompletionStreamer) Metadata() map[string]any {
	return nil
}

func main() {
	ctx := context.Background()

	// Initialize the runtime using the generated bootstrap which wires
	// planners and toolsets for all agents.
	rt, cleanup, err := bootstrap.New(ctx)
	if err != nil {
		log.Fatalf("failed to initialize runtime: %v", err)
	}
	defer cleanup()

	// Example: run the first registered agent with a simple message.
	// Replace this with your own CLI, HTTP server, or integration.
	// Sessions are first-class: create a session explicitly before starting runs.
	// Creating an already-active session is idempotent.
	if _, err := rt.CreateSession(ctx, "demo-session"); err != nil {
		log.Fatalf("failed to create session: %v", err)
	}

	{
		client := chat.NewClient(rt)
		out, err := client.Run(ctx, "demo-session", []*model.Message{
			{
				Role:  model.ConversationRoleUser,
				Parts: []model.Part{model.TextPart{Text: "Hello"}},
			},
		})
		if err != nil {
			log.Fatalf("agent run failed: %v", err)
		}
		fmt.Println("RunID:", out.RunID)
		if out.Final != nil && len(out.Final.Parts) > 0 {
			if tp, ok := out.Final.Parts[0].(model.TextPart); ok {
				fmt.Println("Assistant:", tp.Text)
			}
		}
	}

	{
		client, err := newExampleCompletionClient(string(completions.DraftTask), completions.SpecDraftTask.Result.ExampleJSON)
		if err != nil {
			log.Fatalf("completion client setup failed: %v", err)
		}
		out, err := completions.CompleteDraftTask(ctx, client, &model.Request{
			Messages: []*model.Message{
				{
					Role:  model.ConversationRoleUser,
					Parts: []model.Part{model.TextPart{Text: "Draft a task for preparing a launch checklist."}},
				},
			},
		})
		if err != nil {
			log.Fatalf("completion run failed: %v", err)
		}
		rendered, err := completions.SpecDraftTask.Result.Codec.ToJSON(out.Value)
		if err != nil {
			log.Fatalf("completion render failed: %v", err)
		}
		fmt.Printf("Completion %s: %s\n", completions.DraftTask, rendered)
	}

	{
		client, err := newExampleCompletionClient(string(completions.DraftTask), completions.SpecDraftTask.Result.ExampleJSON)
		if err != nil {
			log.Fatalf("completion stream client setup failed: %v", err)
		}
		stream, err := completions.StreamCompleteDraftTask(ctx, client, &model.Request{
			Messages: []*model.Message{
				{
					Role:  model.ConversationRoleUser,
					Parts: []model.Part{model.TextPart{Text: "Draft a task for preparing a launch checklist."}},
				},
			},
		})
		if err != nil {
			log.Fatalf("completion stream failed to start: %v", err)
		}
		for {
			chunk, err := stream.Recv()
			if err == io.EOF {
				break
			}
			if err != nil {
				log.Fatalf("completion stream failed: %v", err)
			}
			if chunk.Type == model.ChunkTypeCompletionDelta && chunk.CompletionDelta != nil {
				fmt.Printf("Completion delta %s: %s\n", completions.DraftTask, chunk.CompletionDelta.Delta)
			}
			value, ok, err := completions.DecodeDraftTaskChunk(chunk)
			if err != nil {
				log.Fatalf("completion chunk decode failed: %v", err)
			}
			if ok {
				rendered, err := completions.SpecDraftTask.Result.Codec.ToJSON(value)
				if err != nil {
					log.Fatalf("completion stream render failed: %v", err)
				}
				fmt.Printf("Completion stream %s: %s\n", completions.DraftTask, rendered)
			}
		}
		if err := stream.Close(); err != nil {
			log.Fatalf("completion stream close failed: %v", err)
		}
	}
}
