package framework

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerationEnvironmentUsesActiveWorkspace(t *testing.T) {
	t.Setenv("GOWORK", "/tmp/local.go.work")
	t.Setenv("GOFLAGS", "-trimpath")

	environment := generationEnvironment()

	require.Contains(t, environment, "GOWORK=/tmp/local.go.work")
	require.Contains(t, environment, "GOFLAGS=-trimpath")
	require.False(t, slices.Contains(environment, "GOFLAGS=-mod=mod"))
}

func TestGenerationEnvironmentAllowsFixtureDependencyUpdatesWithoutWorkspace(t *testing.T) {
	t.Setenv("GOWORK", "off")
	t.Setenv("GOFLAGS", "-trimpath")

	environment := generationEnvironment()

	require.Equal(t, "GOFLAGS=-mod=mod", environment[len(environment)-1])
}

func TestCleanGeneratedExampleArtifacts(t *testing.T) {
	root := t.TempDir()
	cmdDir := filepath.Join(root, "cmd", "assistant")
	require.NoError(t, os.MkdirAll(cmdDir, 0o750))
	require.NoError(t, os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte("package main\n"), 0o600))
	require.NoError(t, os.WriteFile(
		filepath.Join(root, "generated_test.go"),
		[]byte("// Code generated by goa\npackage assistant\n"),
		0o600,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(root, "manual_test.go"),
		[]byte("package assistant\n"),
		0o600,
	))

	err := cleanGeneratedExampleArtifacts(root)

	require.NoError(t, err)
	_, statErr := os.Stat(filepath.Join(root, "cmd"))
	require.ErrorIs(t, statErr, os.ErrNotExist)
	_, statErr = os.Stat(filepath.Join(root, "generated_test.go"))
	require.ErrorIs(t, statErr, os.ErrNotExist)
	_, statErr = os.Stat(filepath.Join(root, "manual_test.go"))
	require.NoError(t, statErr)
}
