package framework

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunnerRequestsCarryIndependentMetadata(t *testing.T) {
	var messages []map[string]json.RawMessage
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		var message map[string]json.RawMessage
		if !assert.NoError(t, json.NewDecoder(req.Body).Decode(&message)) {
			return
		}
		messages = append(messages, message)
		assert.Equal(t, "2026-07-28", req.Header.Get("MCP-Protocol-Version"))
		assert.Equal(t, "tools/list", req.Header.Get("MCP-Method"))
		assert.Equal(t, "application/json, text/event-stream", req.Header.Get("Accept"))
		w.Header().Set("Content-Type", "application/json")
		_, err := w.Write([]byte(`{"jsonrpc":"2.0","id":1,"result":{"resultType":"complete"}}`))
		assert.NoError(t, err)
	}))
	t.Cleanup(server.Close)
	runner := NewRunner()
	var err error
	runner.baseURL, err = url.Parse(server.URL)
	require.NoError(t, err)
	for _, input := range []map[string]any{nil, {}, {"cursor": "next"}} {
		_, err = runner.executeJSONRPC("tools/list", input, nil, false)
		require.NoError(t, err)
	}
	require.Len(t, messages, 3)
	for _, message := range messages {
		assert.JSONEq(t, `"tools/list"`, string(message["method"]))
		assert.JSONEq(t, `1`, string(message["id"]))
		var params map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(message["params"], &params))
		var meta map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(params["_meta"], &meta))
		assert.JSONEq(t, `"2026-07-28"`, string(meta["io.modelcontextprotocol/protocolVersion"]))
		assert.JSONEq(t, `{}`, string(meta["io.modelcontextprotocol/clientCapabilities"]))
	}
	var last map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(messages[2]["params"], &last))
	assert.JSONEq(t, `"next"`, string(last["cursor"]))
}

func TestRunnerPreservesExplicitInvalidMetadata(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		var message struct {
			Params map[string]json.RawMessage `json:"params"`
		}
		if !assert.NoError(t, json.NewDecoder(req.Body).Decode(&message)) {
			return
		}
		assert.JSONEq(t, `null`, string(message.Params["_meta"]))
		assert.Equal(t, "mismatch", req.Header.Get("MCP-Method"))
		_, err := w.Write([]byte(`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"missing metadata"}}`))
		assert.NoError(t, err)
	}))
	t.Cleanup(server.Close)
	runner := NewRunner()
	var err error
	runner.baseURL, err = url.Parse(server.URL)
	require.NoError(t, err)
	_, err = runner.executeJSONRPC("tools/list", map[string]any{"_meta": nil}, map[string]string{"MCP-Method": "mismatch"}, false)
	assert.ErrorContains(t, err, "-32602")
}

func TestCleanGeneratedExampleArtifacts(t *testing.T) {
	root := t.TempDir()
	cmdDir := filepath.Join(root, "cmd", "assistant")
	require.NoError(t, os.MkdirAll(cmdDir, 0o750))
	require.NoError(t, os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte("package main\n"), 0o600))
	require.NoError(t, os.WriteFile(
		filepath.Join(root, "generated_test.go"),
		[]byte("// Code generated by goa\npackage assistant\n"),
		0o600,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(root, "manual_test.go"),
		[]byte("package assistant\n"),
		0o600,
	))

	err := cleanGeneratedExampleArtifacts(root)

	require.NoError(t, err)
	_, statErr := os.Stat(filepath.Join(root, "cmd"))
	require.ErrorIs(t, statErr, os.ErrNotExist)
	_, statErr = os.Stat(filepath.Join(root, "generated_test.go"))
	require.ErrorIs(t, statErr, os.ErrNotExist)
	_, statErr = os.Stat(filepath.Join(root, "manual_test.go"))
	require.NoError(t, statErr)
}
