// Code generated by Clue Mock Generator v1.2.6, DO NOT EDIT.
//
// Command:
// $ cmg gen goa.design/goa-ai/features/session/mongo/clients/mongo

package mockmongo

import (
	"context"
	"testing"
	"time"

	"goa.design/clue/mock"

	"goa.design/goa-ai/features/session/mongo/clients/mongo"
	"goa.design/goa-ai/runtime/agent/session"
)

type (
	Client struct {
		m *mock.Mock
		t *testing.T
	}

	ClientNameFunc              func() string
	ClientPingFunc              func(p0 context.Context) error
	ClientCreateSessionFunc     func(ctx context.Context, sessionID string, createdAt time.Time) (session.Session, error)
	ClientLoadSessionFunc       func(ctx context.Context, sessionID string) (session.Session, error)
	ClientEndSessionFunc        func(ctx context.Context, sessionID string, endedAt time.Time) (session.Session, error)
	ClientPurgeSessionFunc      func(ctx context.Context, sessionID string) error
	ClientUpsertRunFunc         func(ctx context.Context, run session.RunMeta) error
	ClientLinkChildRunFunc      func(ctx context.Context, parentRunID string, child session.RunMeta) error
	ClientLoadRunFunc           func(ctx context.Context, runID string) (session.RunMeta, error)
	ClientSaveRunSuspensionFunc func(ctx context.Context, runID string, suspension session.RunSuspension) error
	ClientLoadRunSuspensionFunc func(ctx context.Context, runID string) (session.RunSuspension, error)
	ClientListRunsBySessionFunc func(ctx context.Context, sessionID string, statuses []session.RunStatus) ([]session.RunMeta, error)
)

func NewClient(t *testing.T) *Client {
	var (
		m              = &Client{mock.New(), t}
		_ mongo.Client = m
	)
	return m
}

func (m *Client) AddName(f ClientNameFunc) {
	m.m.Add("Name", f)
}

func (m *Client) SetName(f ClientNameFunc) {
	m.m.Set("Name", f)
}

func (m *Client) Name() string {
	if f := m.m.Next("Name"); f != nil {
		return f.(ClientNameFunc)()
	}
	m.t.Helper()
	m.t.Error("unexpected Name call")
	return ""
}

func (m *Client) AddPing(f ClientPingFunc) {
	m.m.Add("Ping", f)
}

func (m *Client) SetPing(f ClientPingFunc) {
	m.m.Set("Ping", f)
}

func (m *Client) Ping(p0 context.Context) error {
	if f := m.m.Next("Ping"); f != nil {
		return f.(ClientPingFunc)(p0)
	}
	m.t.Helper()
	m.t.Error("unexpected Ping call")
	return nil
}

func (m *Client) AddCreateSession(f ClientCreateSessionFunc) {
	m.m.Add("CreateSession", f)
}

func (m *Client) SetCreateSession(f ClientCreateSessionFunc) {
	m.m.Set("CreateSession", f)
}

func (m *Client) CreateSession(ctx context.Context, sessionID string, createdAt time.Time) (session.Session, error) {
	if f := m.m.Next("CreateSession"); f != nil {
		return f.(ClientCreateSessionFunc)(ctx, sessionID, createdAt)
	}
	m.t.Helper()
	m.t.Error("unexpected CreateSession call")
	return session.Session{}, nil
}

func (m *Client) AddLoadSession(f ClientLoadSessionFunc) {
	m.m.Add("LoadSession", f)
}

func (m *Client) SetLoadSession(f ClientLoadSessionFunc) {
	m.m.Set("LoadSession", f)
}

func (m *Client) LoadSession(ctx context.Context, sessionID string) (session.Session, error) {
	if f := m.m.Next("LoadSession"); f != nil {
		return f.(ClientLoadSessionFunc)(ctx, sessionID)
	}
	m.t.Helper()
	m.t.Error("unexpected LoadSession call")
	return session.Session{}, nil
}

func (m *Client) AddEndSession(f ClientEndSessionFunc) {
	m.m.Add("EndSession", f)
}

func (m *Client) SetEndSession(f ClientEndSessionFunc) {
	m.m.Set("EndSession", f)
}

func (m *Client) EndSession(ctx context.Context, sessionID string, endedAt time.Time) (session.Session, error) {
	if f := m.m.Next("EndSession"); f != nil {
		return f.(ClientEndSessionFunc)(ctx, sessionID, endedAt)
	}
	m.t.Helper()
	m.t.Error("unexpected EndSession call")
	return session.Session{}, nil
}

func (m *Client) AddPurgeSession(f ClientPurgeSessionFunc) {
	m.m.Add("PurgeSession", f)
}

func (m *Client) SetPurgeSession(f ClientPurgeSessionFunc) {
	m.m.Set("PurgeSession", f)
}

func (m *Client) PurgeSession(ctx context.Context, sessionID string) error {
	if f := m.m.Next("PurgeSession"); f != nil {
		return f.(ClientPurgeSessionFunc)(ctx, sessionID)
	}
	m.t.Helper()
	m.t.Error("unexpected PurgeSession call")
	return nil
}

func (m *Client) AddUpsertRun(f ClientUpsertRunFunc) {
	m.m.Add("UpsertRun", f)
}

func (m *Client) SetUpsertRun(f ClientUpsertRunFunc) {
	m.m.Set("UpsertRun", f)
}

func (m *Client) UpsertRun(ctx context.Context, run session.RunMeta) error {
	if f := m.m.Next("UpsertRun"); f != nil {
		return f.(ClientUpsertRunFunc)(ctx, run)
	}
	m.t.Helper()
	m.t.Error("unexpected UpsertRun call")
	return nil
}

func (m *Client) AddLinkChildRun(f ClientLinkChildRunFunc) {
	m.m.Add("LinkChildRun", f)
}

func (m *Client) SetLinkChildRun(f ClientLinkChildRunFunc) {
	m.m.Set("LinkChildRun", f)
}

func (m *Client) LinkChildRun(ctx context.Context, parentRunID string, child session.RunMeta) error {
	if f := m.m.Next("LinkChildRun"); f != nil {
		return f.(ClientLinkChildRunFunc)(ctx, parentRunID, child)
	}
	m.t.Helper()
	m.t.Error("unexpected LinkChildRun call")
	return nil
}

func (m *Client) AddLoadRun(f ClientLoadRunFunc) {
	m.m.Add("LoadRun", f)
}

func (m *Client) SetLoadRun(f ClientLoadRunFunc) {
	m.m.Set("LoadRun", f)
}

func (m *Client) LoadRun(ctx context.Context, runID string) (session.RunMeta, error) {
	if f := m.m.Next("LoadRun"); f != nil {
		return f.(ClientLoadRunFunc)(ctx, runID)
	}
	m.t.Helper()
	m.t.Error("unexpected LoadRun call")
	return session.RunMeta{}, nil
}

func (m *Client) AddSaveRunSuspension(f ClientSaveRunSuspensionFunc) {
	m.m.Add("SaveRunSuspension", f)
}

func (m *Client) SetSaveRunSuspension(f ClientSaveRunSuspensionFunc) {
	m.m.Set("SaveRunSuspension", f)
}

func (m *Client) SaveRunSuspension(ctx context.Context, runID string, suspension session.RunSuspension) error {
	if f := m.m.Next("SaveRunSuspension"); f != nil {
		return f.(ClientSaveRunSuspensionFunc)(ctx, runID, suspension)
	}
	m.t.Helper()
	m.t.Error("unexpected SaveRunSuspension call")
	return nil
}

func (m *Client) AddLoadRunSuspension(f ClientLoadRunSuspensionFunc) {
	m.m.Add("LoadRunSuspension", f)
}

func (m *Client) SetLoadRunSuspension(f ClientLoadRunSuspensionFunc) {
	m.m.Set("LoadRunSuspension", f)
}

func (m *Client) LoadRunSuspension(ctx context.Context, runID string) (session.RunSuspension, error) {
	if f := m.m.Next("LoadRunSuspension"); f != nil {
		return f.(ClientLoadRunSuspensionFunc)(ctx, runID)
	}
	m.t.Helper()
	m.t.Error("unexpected LoadRunSuspension call")
	return session.RunSuspension{}, nil
}

func (m *Client) AddListRunsBySession(f ClientListRunsBySessionFunc) {
	m.m.Add("ListRunsBySession", f)
}

func (m *Client) SetListRunsBySession(f ClientListRunsBySessionFunc) {
	m.m.Set("ListRunsBySession", f)
}

func (m *Client) ListRunsBySession(ctx context.Context, sessionID string, statuses []session.RunStatus) ([]session.RunMeta, error) {
	if f := m.m.Next("ListRunsBySession"); f != nil {
		return f.(ClientListRunsBySessionFunc)(ctx, sessionID, statuses)
	}
	m.t.Helper()
	m.t.Error("unexpected ListRunsBySession call")
	return nil, nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
