// Code generated by goa v3.22.6, DO NOT EDIT.
//
// Agents bootstrap (internal)
//
// Command:
// $ goa example example.com/assistant/design

package bootstrap

import (
	"context"
	"flag"
	"fmt"

	chat "example.com/assistant/gen/orchestrator/agents/chat"
	plannerchat "example.com/assistant/internal/agents/chat/planner"
	agentsruntime "goa.design/goa-ai/runtime/agents/runtime"
	mcpruntime "goa.design/goa-ai/runtime/mcp"
)

// Package bootstrap wires the goa-ai runtime and registers generated agents.
// This scaffold is application-owned: edit and maintain it; it is not re-generated
// by `goa gen`. Use it from your cmd main or workers to initialize agents.

// Define flags for MCP endpoints (if any). Pass values via your cmd main.
var (
	mcpAssistantAssistantMcpEndpoint = flag.String("mcp-assistant-assistant-mcp-endpoint", "", "MCP assistant.assistant-mcp HTTP endpoint (e.g., http://127.0.0.1:8080/rpc)")
)

// New constructs a minimal runtime and registers all agents for this service.
// Replace options (engine, stores, telemetry) as you adopt production wiring.
func New(ctx context.Context) (*agentsruntime.Runtime, func(), error) {
	rt := agentsruntime.New(agentsruntime.Options{})
	cleanup := func() {}

	// Register agents with example planners. Replace with your own planner impls.
	{
		cfg := chat.ChatAgentConfig{Planner: plannerchat.New()}
		// Configure MCP callers for external toolsets.
		cfg.MCPCallers = map[string]mcpruntime.Caller{}
		if mcpAssistantAssistantMcpEndpoint != nil && *mcpAssistantAssistantMcpEndpoint != "" {
			caller, err := mcpruntime.NewHTTPCaller(ctx, mcpruntime.HTTPOptions{Endpoint: *mcpAssistantAssistantMcpEndpoint})
			if err != nil {
				return nil, nil, err
			}
			cfg.MCPCallers[chat.ChatAssistantAssistantMcpToolsetID] = caller
		} else {
			cfg.MCPCallers[chat.ChatAssistantAssistantMcpToolsetID] = mcpruntime.CallerFunc(func(ctx context.Context, req mcpruntime.CallRequest) (mcpruntime.CallResponse, error) {
				return mcpruntime.CallResponse{}, fmt.Errorf("configure MCP caller for %s via -mcp-assistant-assistant-mcp-endpoint flag", "assistant.assistant-mcp")
			})
		}
		if err := chat.RegisterChatAgent(ctx, rt, cfg); err != nil {
			return nil, nil, err
		}
	}

	return rt, cleanup, nil
}
