// Code generated by Clue Mock Generator v1.2.3, DO NOT EDIT.
//
// Command:
// $ cmg gen goa.design/goa-ai/features/memory/mongo/clients/mongo

package mockmongo

import (
	"context"
	"testing"

	"goa.design/clue/mock"

	"goa.design/goa-ai/features/memory/mongo/clients/mongo"
	"goa.design/goa-ai/runtime/agents/memory"
)

type (
	Client struct {
		m *mock.Mock
		t *testing.T
	}

	ClientNameFunc         func() string
	ClientPingFunc         func(p0 context.Context) error
	ClientLoadRunFunc      func(ctx context.Context, agentID, runID string) (memory.Snapshot, error)
	ClientAppendEventsFunc func(ctx context.Context, agentID, runID string, events []memory.Event) error
)

func NewClient(t *testing.T) *Client {
	var (
		m              = &Client{mock.New(), t}
		_ mongo.Client = m
	)
	return m
}

func (m *Client) AddName(f ClientNameFunc) {
	m.m.Add("Name", f)
}

func (m *Client) SetName(f ClientNameFunc) {
	m.m.Set("Name", f)
}

func (m *Client) Name() string {
	if f := m.m.Next("Name"); f != nil {
		return f.(ClientNameFunc)()
	}
	m.t.Helper()
	m.t.Error("unexpected Name call")
	return ""
}

func (m *Client) AddPing(f ClientPingFunc) {
	m.m.Add("Ping", f)
}

func (m *Client) SetPing(f ClientPingFunc) {
	m.m.Set("Ping", f)
}

func (m *Client) Ping(p0 context.Context) error {
	if f := m.m.Next("Ping"); f != nil {
		return f.(ClientPingFunc)(p0)
	}
	m.t.Helper()
	m.t.Error("unexpected Ping call")
	return nil
}

func (m *Client) AddLoadRun(f ClientLoadRunFunc) {
	m.m.Add("LoadRun", f)
}

func (m *Client) SetLoadRun(f ClientLoadRunFunc) {
	m.m.Set("LoadRun", f)
}

func (m *Client) LoadRun(ctx context.Context, agentID, runID string) (memory.Snapshot, error) {
	if f := m.m.Next("LoadRun"); f != nil {
		return f.(ClientLoadRunFunc)(ctx, agentID, runID)
	}
	m.t.Helper()
	m.t.Error("unexpected LoadRun call")
	return memory.Snapshot{}, nil
}

func (m *Client) AddAppendEvents(f ClientAppendEventsFunc) {
	m.m.Add("AppendEvents", f)
}

func (m *Client) SetAppendEvents(f ClientAppendEventsFunc) {
	m.m.Set("AppendEvents", f)
}

func (m *Client) AppendEvents(ctx context.Context, agentID, runID string, events []memory.Event) error {
	if f := m.m.Next("AppendEvents"); f != nil {
		return f.(ClientAppendEventsFunc)(ctx, agentID, runID, events)
	}
	m.t.Helper()
	m.t.Error("unexpected AppendEvents call")
	return nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
