// Package testutil compares generated output with checked-in golden files.
// Tests may update those files with -update or -u. Every comparison normalizes
// generated Goa versions and line endings so unrelated tool versions do not
// change the expected output.
package testutil

import (
	"bytes"
	"encoding/json"
	"flag"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

var (
	update = flag.Bool("update", false, "update golden files")
	u      = flag.Bool("u", false, "update golden files (shorthand)")

	goHeaderVersionRE    = regexp.MustCompile(`(?m)^// Code generated by goa(?: v[^,]+)?, DO NOT EDIT\.`)
	protoHeaderVersionRE = regexp.MustCompile(
		`(?m)^// Code generated with goa v[^,]+, DO NOT EDIT\.`,
	)
)

// AssertString compares text with a golden file.
func AssertString(t testing.TB, goldenPath, got string) {
	t.Helper()
	compareGolden(t, goldenPath, []byte(got))
}

// AssertJSON formats JSON before comparing it with a golden file.
func AssertJSON(t testing.TB, goldenPath string, got []byte) {
	t.Helper()
	var value any
	if err := json.Unmarshal(got, &value); err == nil {
		if formatted, err := json.MarshalIndent(value, "", "  "); err == nil {
			got = formatted
		}
	}
	compareGolden(t, goldenPath, got)
}

// AssertGo formats Go source before comparing it with a golden file.
func AssertGo(t testing.TB, goldenPath, got string) {
	t.Helper()
	content := []byte(got)
	if formatted, err := format.Source(content); err == nil {
		content = formatted
	}
	compareGolden(t, goldenPath, content)
}

// compareGolden updates or compares one explicit golden file path.
func compareGolden(t testing.TB, goldenPath string, got []byte) {
	t.Helper()
	got = prepareContent(goldenPath, got)
	if *update || *u {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o750); err != nil {
			t.Fatalf("create golden file directory %q: %v", filepath.Dir(goldenPath), err)
		}
		if err := os.WriteFile(goldenPath, got, 0o600); err != nil {
			t.Fatalf("update golden file %q: %v", goldenPath, err)
		}
		t.Logf("Updated golden file: %s", goldenPath)
		return
	}

	want, err := os.ReadFile(goldenPath) //nolint:gosec // Tests choose the golden file path.
	if os.IsNotExist(err) {
		t.Fatalf("golden file %q does not exist (run with -update to create)", goldenPath)
	}
	if err != nil {
		t.Fatalf("read golden file %q: %v", goldenPath, err)
	}
	want = prepareContent(goldenPath, want)
	if !bytes.Equal(got, want) {
		require.Equalf(t, string(want), string(got), "golden file mismatch for %q", goldenPath)
		t.Log("Run with -update to update the golden file")
	}
}

// prepareContent normalizes formatting that must not depend on the local tool version.
func prepareContent(goldenPath string, content []byte) []byte {
	if strings.HasSuffix(goldenPath, ".json") || strings.HasSuffix(goldenPath, ".json.golden") {
		var value any
		if err := json.Unmarshal(content, &value); err == nil {
			if formatted, err := json.MarshalIndent(value, "", "  "); err == nil {
				content = formatted
			}
		}
	}
	if formatted, err := format.Source(content); err == nil {
		content = formatted
		content = goHeaderVersionRE.ReplaceAll(content, []byte("// Code generated by goa vX, DO NOT EDIT."))
	}
	content = protoHeaderVersionRE.ReplaceAll(
		content,
		[]byte("// Code generated with goa vX, DO NOT EDIT."),
	)
	content = bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))

	lines := strings.Split(string(content), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	content = []byte(strings.Join(lines, "\n"))
	if len(content) > 0 && content[len(content)-1] != '\n' {
		content = append(content, '\n')
	}
	return content
}
