// Code generated by Clue Mock Generator v1.2.3, DO NOT EDIT.
//
// Command:
// $ cmg gen goa.design/goa-ai/features/prompt/mongo/clients/mongo

package mockmongo

import (
	"context"
	"testing"

	"goa.design/clue/mock"

	"goa.design/goa-ai/features/prompt/mongo/clients/mongo"
	"goa.design/goa-ai/runtime/agent/prompt"
)

type (
	Client struct {
		m *mock.Mock
		t *testing.T
	}

	ClientNameFunc    func() string
	ClientPingFunc    func(p0 context.Context) error
	ClientResolveFunc func(ctx context.Context, promptID prompt.Ident, scope prompt.Scope) (*prompt.Override, error)
	ClientSetFunc     func(ctx context.Context, promptID prompt.Ident, scope prompt.Scope, template string, metadata map[string]string) error
	ClientHistoryFunc func(ctx context.Context, promptID prompt.Ident) ([]*prompt.Override, error)
	ClientListFunc    func(ctx context.Context) ([]*prompt.Override, error)
)

func NewClient(t *testing.T) *Client {
	var (
		m              = &Client{mock.New(), t}
		_ mongo.Client = m
	)
	return m
}

func (m *Client) AddName(f ClientNameFunc) {
	m.m.Add("Name", f)
}

func (m *Client) SetName(f ClientNameFunc) {
	m.m.Set("Name", f)
}

func (m *Client) Name() string {
	if f := m.m.Next("Name"); f != nil {
		return f.(ClientNameFunc)()
	}
	m.t.Helper()
	m.t.Error("unexpected Name call")
	return ""
}

func (m *Client) AddPing(f ClientPingFunc) {
	m.m.Add("Ping", f)
}

func (m *Client) SetPing(f ClientPingFunc) {
	m.m.Set("Ping", f)
}

func (m *Client) Ping(p0 context.Context) error {
	if f := m.m.Next("Ping"); f != nil {
		return f.(ClientPingFunc)(p0)
	}
	m.t.Helper()
	m.t.Error("unexpected Ping call")
	return nil
}

func (m *Client) AddResolve(f ClientResolveFunc) {
	m.m.Add("Resolve", f)
}

func (m *Client) SetResolve(f ClientResolveFunc) {
	m.m.Set("Resolve", f)
}

func (m *Client) Resolve(ctx context.Context, promptID prompt.Ident, scope prompt.Scope) (*prompt.Override, error) {
	if f := m.m.Next("Resolve"); f != nil {
		return f.(ClientResolveFunc)(ctx, promptID, scope)
	}
	m.t.Helper()
	m.t.Error("unexpected Resolve call")
	return nil, nil
}

func (m *Client) AddSet(f ClientSetFunc) {
	m.m.Add("Set", f)
}

func (m *Client) SetSet(f ClientSetFunc) {
	m.m.Set("Set", f)
}

func (m *Client) Set(ctx context.Context, promptID prompt.Ident, scope prompt.Scope, template string, metadata map[string]string) error {
	if f := m.m.Next("Set"); f != nil {
		return f.(ClientSetFunc)(ctx, promptID, scope, template, metadata)
	}
	m.t.Helper()
	m.t.Error("unexpected Set call")
	return nil
}

func (m *Client) AddHistory(f ClientHistoryFunc) {
	m.m.Add("History", f)
}

func (m *Client) SetHistory(f ClientHistoryFunc) {
	m.m.Set("History", f)
}

func (m *Client) History(ctx context.Context, promptID prompt.Ident) ([]*prompt.Override, error) {
	if f := m.m.Next("History"); f != nil {
		return f.(ClientHistoryFunc)(ctx, promptID)
	}
	m.t.Helper()
	m.t.Error("unexpected History call")
	return nil, nil
}

func (m *Client) AddList(f ClientListFunc) {
	m.m.Add("List", f)
}

func (m *Client) SetList(f ClientListFunc) {
	m.m.Set("List", f)
}

func (m *Client) List(ctx context.Context) ([]*prompt.Override, error) {
	if f := m.m.Next("List"); f != nil {
		return f.(ClientListFunc)(ctx)
	}
	m.t.Helper()
	m.t.Error("unexpected List call")
	return nil, nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
