// Code generated by goa v3.22.6, DO NOT EDIT.
//
// Example planner stub for chat
//
// Command:
// $ goa example example.com/assistant/design

package main

import (
	"context"

	"goa.design/goa-ai/agents/runtime/planner"
)

// newChatPlanner returns a trivial planner implementation used by the example bootstrap.
func newChatPlanner() planner.Planner { return &exampleChatPlanner{} }

type exampleChatPlanner struct{}

func (p *exampleChatPlanner) PlanStart(ctx context.Context, in planner.PlanInput) (planner.PlanResult, error) {
	// Minimal example: produce a generic assistant reply when no tools are requested.
	return planner.PlanResult{FinalResponse: &planner.FinalResponse{Message: planner.AgentMessage{Role: "assistant", Content: "Hello from example planner."}}}, nil
}

func (p *exampleChatPlanner) PlanResume(ctx context.Context, in planner.PlanResumeInput) (planner.PlanResult, error) {
	return planner.PlanResult{FinalResponse: &planner.FinalResponse{Message: planner.AgentMessage{Role: "assistant", Content: "Done."}}}, nil
}
