// Code generated by goa v3.22.6, DO NOT EDIT.
//
// Agents bootstrap helper
//
// Command:
// $ goa example example.com/assistant/design

package main

import (
	"context"
	"fmt"

	chat "example.com/assistant/gen/orchestrator/agents/chat"
	temporalclient "go.temporal.io/sdk/client"
	runtimeTemporal "goa.design/goa-ai/agents/runtime/engine/temporal"
	meminmem "goa.design/goa-ai/agents/runtime/memory/inmem"
	runinmem "goa.design/goa-ai/agents/runtime/run/inmem"
	agentsruntime "goa.design/goa-ai/agents/runtime/runtime"
	mcpruntime "goa.design/goa-ai/features/mcp/runtime"
)

// bootstrapAgents initializes the workflow engine + runtime and registers agents.
// The caller is responsible for closing the returned cleanup function.
func bootstrapAgents(ctx context.Context) (*agentsruntime.Runtime, func(), error) {
	eng, err := runtimeTemporal.New(runtimeTemporal.Options{
		ClientOptions: &temporalclient.Options{
			HostPort:  "127.0.0.1:7233",
			Namespace: "default",
		},
		WorkerOptions: runtimeTemporal.WorkerOptions{TaskQueue: "orchestrator.agents"},
	})
	if err != nil {
		return nil, nil, err
	}
	rt := agentsruntime.New(agentsruntime.Options{
		Engine:      eng,
		MemoryStore: meminmem.New(),
		RunStore:    runinmem.New(),
	})

	// Register all agents in this service.
	cfgChat := chat.ChatAgentConfig{
		Planner: newChatPlanner(),
	}
	callersChat, err := configureChatMCPCallers(ctx)
	if err != nil {
		_ = eng.Close()
		return nil, nil, err
	}
	cfgChat.MCPCallers = callersChat
	if err := chat.RegisterChatAgent(ctx, rt, cfgChat); err != nil {
		_ = eng.Close()
		return nil, nil, err
	}

	return rt, func() { _ = eng.Close() }, nil
}

// configureChatMCPCallers returns the MCP callers required by the chat agent.
// Replace the stubs with real callers (e.g., mcpruntime.NewHTTPCaller) before running agents.
func configureChatMCPCallers(ctx context.Context) (map[string]mcpruntime.Caller, error) {
	_ = ctx
	callers := make(map[string]mcpruntime.Caller, 1)
	callers[chat.ChatAssistantAssistantMcpToolsetID] = mcpruntime.CallerFunc(func(ctx context.Context, req mcpruntime.CallRequest) (mcpruntime.CallResponse, error) {
		return mcpruntime.CallResponse{}, fmt.Errorf("configure MCP caller for %s in cmd/orchestrator/agents_bootstrap.go", "assistant.assistant-mcp")
	})
	return callers, nil
}
