// Code generated by goa, DO NOT EDIT.
//
// Planner stub for ChatAgent
//
// Command:
// $ goa example example.com/quickstart/design

package planner

import (
	"context"
	"fmt"

	gentool "example.com/quickstart/gen/orchestrator/toolsets/helpers"
	model "goa.design/goa-ai/runtime/agent/model"
	"goa.design/goa-ai/runtime/agent/planner"
)

// New returns a minimal planner implementation for Chat used by example bootstrap.
// Replace with your production planner integrating your LLM of choice.
func New() planner.Planner { return &examplePlanner{} }

// examplePlanner is a minimal, stateless implementation of planner.Planner used by
// the example bootstrap. The planner acts as the agent's "brain": it reasons over
// conversation messages, decides whether to request tool executions, and produces
// final assistant responses. Production planners typically invoke LLMs via
// registered planner-scoped model clients (in.Agent.PlannerModelClient(...)) or
// pair ModelClient with planner.ConsumeStream, which only drains the validated
// stream. The runtime journal publishes selected presentation and usage.
type examplePlanner struct{}

func (p *examplePlanner) Decide(ctx context.Context, tool string) string {
	return "reason"
}

func (p *examplePlanner) PlanStart(ctx context.Context, in *planner.PlanInput) (*planner.PlanResult, error) {
	// Check for deterministic routing (Passthrough)
	if in.RunContext.Tool != "" {
		route := p.Decide(ctx, string(in.RunContext.Tool))
		if route == "passthrough" {
			// Deterministic passthrough: forward args directly to the target tool.
			// For this example stub, we don't have the target mapping (it's in the DSL but not fully exposed here yet).
			// Real implementation would use the Passthrough metadata to construct the ToolRequest.
			// This stub just falls through to the default response.
		}
	}
	args, err := gentool.AnswerPayloadCodec.FromJSON(gentool.SpecAnswer.Payload.ExampleJSON)
	if err != nil {
		return nil, fmt.Errorf("decode generated helpers.answer example: %w", err)
	}
	return &planner.PlanResult{
		ToolCalls: []planner.ToolRequest{
			gentool.NewAnswerCall("quickstart-helpers.answer", args),
		},
	}, nil
}

func (p *examplePlanner) PlanResume(ctx context.Context, in *planner.PlanResumeInput) (*planner.PlanResult, error) {
	if len(in.ToolOutputs) != 1 {
		return nil, fmt.Errorf("expected one helpers.answer result, got %d", len(in.ToolOutputs))
	}
	output := in.ToolOutputs[0]
	if output.Name != gentool.Answer || output.ToolCallID != "quickstart-helpers.answer" {
		return nil, fmt.Errorf("unexpected tool result %s (%s)", output.Name, output.ToolCallID)
	}
	if output.Failure != nil {
		return nil, fmt.Errorf("helpers.answer failed: %s", output.Failure.Error.Message)
	}
	answer := fmt.Sprintf("Tool %s returned %s", output.Name, output.Result)
	return &planner.PlanResult{
		FinalResponse: &planner.FinalResponse{
			Message: &model.Message{
				Role:  model.ConversationRoleAssistant,
				Parts: []model.Part{model.TextPart{Text: answer}},
			},
		},
	}, nil
}
